### PR TITLE
Pr/2

### PR DESCRIPTION
**Pull request by zerogetsamgow**
I don't know what I have done here.

I made changes to master before seeing your pull request.

I think I have now merged the master into your pull request with more changes, which now results in me needing to make a sub pull request.

Also, using joins and filter to subset data for charts means that I can't set breaks=teams$team, drops =false to ensure all teams are shown in every chart/plot.

### CODE REVIEW

**Comment by iangow** [comment]
Much to learn, grasshopper. Say @iangow for me to see a comment on a thread on which I'm not associated (I wouldn't see this normally, as I didn't create this pull request, etc). 

You don't need to do pull requests of your _own_ changes. Also `git pull --rebase=preserve` is better than default `git pull`. I suspect the GitHub interface obscures the flexibility that Git gives you. 

If you want all teams, you just need to the right kind of join, etc. Look at `teams %>% left_join(games)` for example. 

What does it mean to "include" a team that doesn't get a bar due to `subset`?

**Comment by zerogetsamgow** [comment]
Git led me to believe that I was making a pull request to your pull
request. As I said, github is awful.

**Comment by iangow** [comment]
"Pull request" is (I believe) GitHub's, not Git's, terminology. You're basically doing a merge and can do so with full Git flexibility. Maybe one of the Git books explains fully. I've never dealt with a pull request, so I'm no expert. 

You should not have `.Rhistory` in the repository. Go [here](http://stackoverflow.com/questions/7527982/applying-gitignore-to-committed-files) to see how to get Git to ignore it. If you set up projects using RStudio initially, it takes care of these details. 

I think you want to do the scraping and cleaning in one place. Effectively you are making a version of the database that underlies `afltables.com`. Then I think you want to prepare the data for each plot outside the `ggplot` function so you can see it and do it more easily. `ggplot2` can be a little too [implicit](https://www.python.org/dev/peps/pep-0020/) at times (eg, summing stuff for plots) for my tastes and I think you want to make things clearer in the code than `ggplot` needs.

**Comment by iangow** [comment]
This works to remove `.Rhistory`: 
- First, `git rm --cached .Rhistory` in Terminal.
- Second, commit the deletion using Git.

As you can see below, the first step doesn't delete the file, just removes it from Git.

`````` bash
Ians-MacBook:afltables igow$ git rm --cached .Rhistory 
rm '.Rhistory'
Ians-MacBook:afltables igow$ ls -hlta .Rhistory 
-rw-r--r--  1 igow  staff    16K May 18 18:38 .Rhistory```
``````

**Comment by iangow** [comment]
I recommend SourceTree. Below you can see that I have mapped your GitHub repository to a local branch `sam` (I did this using the SourceTree GUI, but there's a `git` command for this, of course).

afltables

So I can fetch your changes and merge locally with more control than might be easily obtained with "accept pull request" on GitHub's website.

**Comment by zerogetsamgow** [comment]
I downloaded github desktop. I have not been able to do anything on the
website.

**Comment by iangow** [comment]
I think GitHub Desktop is a bit too simple to allow you to handle this in a nuanced way (eg, accepting some changes, rejecting others). And handling pull requests is dropping you in the deep end of Git. Creating a new branch for what you had was a good idea. 

There's a learning curve for Git, but I think it is well worth the effort, especially if you're collaborating with someone else. If you were supervising a budding analyst, it would be a great way to mentor him or her. It's just a pain (I guess) that it's piled onto learning dplyr, etc, at the same time.

**Comment by zerogetsamgow** [comment]
And tableau (started with that today).

**Pull request merged**
